Update helm chart

diff --git a/nirmata-kube-controller/templates/nirmata-kube-controller.yaml b/nirmata-kube-controller/templates/nirmata-kube-controller.yaml
--- a/nirmata-kube-controller/templates/nirmata-kube-controller.yaml
+++ b/nirmata-kube-controller/templates/nirmata-kube-controller.yaml
@@ -126,6 +126,7 @@ rules:
 - apiGroups: [""]
   resources:
   - nodes
+  - nodes/metrics
   - componentstatuses
   verbs:
   - get
@@ -274,8 +275,14 @@ spec:
         {{ end }}
         - -api-token-secret
         - {{ .Values.apiTokenSecret }}
+        - -onboarding-token
+        - {{ .Values.clusterOnboardingToken }}
         {{- if .Values.kubeController.insecure }}
         - -insecure
+        {{- end }}
+        {{- if .Values.isNpmOnly }}
+        - -gatewayUrl
+        - {{ .Values.nirmataURL | default "wss://nirmata.io/tunnels" | replace "/tunnels" "/gateway-service" }}
         {{- end }}
         env:
         - name: URL
@@ -339,10 +346,17 @@ spec:
         configMap:
           name: {{ if .Values.kubeController.customCaConfigMap }}{{ .Values.kubeController.customCaConfigMap }}{{ else }}nirmata-ca-cert{{ end }}
       {{- end }}
+      {{- if .Values.kubeController.nodeSelector }}
+      nodeSelector:
+        {{- toYaml .Values.kubeController.nodeSelector | nindent 8 }}
+      {{- end }}
       tolerations:
       - effect: NoSchedule
         key: node-role.kubernetes.io/master
         operator: Exists
+      {{- with .Values.kubeController.tolerations }}
+        {{- toYaml . | nindent 6 }}
+      {{- end }}
 ---
 apiVersion: v1
 kind: ConfigMap
@@ -356,18 +370,52 @@ data:
         config:
           scrape_configs:
           - job_name: kyverno
-            scrape_interval: 1m
+            scrape_interval: 10s
             static_configs:
             - targets: [kyverno-svc-metrics.kyverno.svc.cluster.local:8000]
             metric_relabel_configs:
             - source_labels: [__name__]
-              regex: (kyverno_admission_review_duration_seconds.*|kyverno_policy_execution_duration_seconds.*|kyverno_policy_results_total|kyverno_policy_rule_info_total|kyverno_admission_requests_total|kyverno_controller_reconcile_total|kyverno_controller_requeue_total|kyverno_controller_drop_total)
+              regex: (kyverno_http_requests_duration_seconds_bucket.*|kyverno_policy_execution_duration_seconds_bucket.*|kyverno_client_queries_total.*|kyverno_admission_review_duration_seconds.*|kyverno_policy_execution_duration_seconds.*|kyverno_policy_results_total|kyverno_policy_rule_info_total|kyverno_admission_requests_total|kyverno_controller_reconcile_total|kyverno_controller_requeue_total|kyverno_controller_drop_total)
               action: keep
+          - job_name: kubelet
+            scrape_interval: 10s
+            scheme: https
+            tls_config:
+              insecure_skip_verify: true
+            bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
+            kubernetes_sd_configs:
+            - role: node
+            relabel_configs:
+            - source_labels: [__meta_kubernetes_node_name]
+              target_label: instance
+            metrics_path: /metrics/cadvisor
+            metric_relabel_configs:
+            - source_labels: [__name__]
+              regex: (container_memory_usage_bytes.*|container_cpu_usage_seconds_total)
+              action: keep
+          - job_name: 'kyverno-operator'
+            kubernetes_sd_configs:
+              - role: pod
+                namespaces:
+                  names:
+                    - nirmata-system
+            relabel_configs:
+              - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
+                action: keep
+                regex: true
+              - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_name]
+                action: keep
+                regex: nirmata-kyverno-operator
+              - source_labels: [__address__]
+                action: keep
+                regex: .*:8080$
+              - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
+                action: replace
+                target_label: __metrics_path__
+                regex: (kyverno_.*)
     exporters:
       prometheusremotewrite:
-        endpoint: https://staging.nirmata.co/host-gateway/metrics-receiver
-        external_labels:
-          clusterId: 8b0919f4-2ed8-4c7d-94cc-f04ab849a2a7
+        endpoint: https://{{ include "controller.metricsEndpointDomain" . }}{{ if .Values.isNpmOnly }}/gateway-service{{ else }}/host-gateway{{ end }}/metrics-receiver
         remote_write_queue:
           queue_size: 2000
           num_consumers: 1
@@ -403,6 +451,29 @@ spec:
         app.kubernetes.io/instance: nirmata
         app.kubernetes.io/name: nirmata
     spec:
+      initContainers:
+      - name: wait-for-tenantid
+        image: bitnami/kubectl:latest
+        command:
+        - /bin/sh
+        - -c
+        - |
+          echo "Waiting for external_labels.tenantId in ConfigMap..."
+          while true; do
+            config=$(kubectl get configmap otel-agent-config -n {{ .Values.namespace }} -o jsonpath='{.data.config\.yaml}')
+            echo "$config" | grep -q "external_labels:" && echo "$config" | grep -q "tenantId:"
+            if [ $? -eq 0 ]; then
+              echo "Found external_labels and tenantId!"
+              break
+            fi
+            echo "Not found yet, sleeping..."
+            sleep 5
+          done
+        securityContext:
+          runAsNonRoot: true
+          readOnlyRootFilesystem: true
+      serviceAccountName: nirmata
+      serviceAccount: nirmata
       containers:
       - name: otel-agent
         command:
@@ -458,3 +529,11 @@ spec:
       {{- end }}
       imagePullSecrets:
       - name: {{ default "nirmata-controller-registry-secret" .Values.global.imagePullSecretName }}
+      {{- if .Values.otelAgent.nodeSelector }}
+      nodeSelector:
+        {{- toYaml .Values.otelAgent.nodeSelector | nindent 8 }}
+      {{- end }}
+      {{- if .Values.otelAgent.tolerations }}
+      tolerations:
+        {{- toYaml .Values.otelAgent.tolerations | nindent 6 }}
+      {{- end }}
